name: Build Android APK

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      NODE_VERSION: 18
      JAVA_VERSION: '17'
      ANDROID_COMPILE_SDK: 33
      ANDROID_BUILD_TOOLS: '33.0.0'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Add iOS bundle identifier
        run: |
          # Add dummy iOS bundle identifier to app.json
          jq '.expo.ios.bundleIdentifier = "com.example.dummy"' app.json > temp.json && mv temp.json app.json
          cat app.json

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses || true
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-${{ env.ANDROID_COMPILE_SDK }}"

      - name: Prebuild project (Android only)
        run: npx expo prebuild --platform android

      - name: Build Android APK
        run: |
          cd android
          ./gradlew clean assembleRelease -Pandroid.debug.obsoleteApi=true --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: USDT-Deposit
          path: android/app/build/outputs/apk/release/app-release.apk